[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
evm_version = 'paris' 
optimizer = true
optimizer_runs = 20_000

fs_permissions = [{ access = "read", path = "./"}]

dynamic_test_linking = true

[fuzz]
runs = 1024

[rpc_endpoints]
bsc_testnet = "https://data-seed-prebsc-1-s1.bnbchain.org:8545"
bsc = "https://bsc-dataseed.bnbchain.org"

[etherscan]
bsc = { key = "${ETHERSCAN_API_KEY}", chain = 56 }
bsc_testnet = { key = "${ETHERSCAN_API_KEY}", chain = 97 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config